---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
name: Build
jobs:
  release:
    name: Release
#    runs-on: [self-hosted, heavy]
    runs-on: ubuntu-latest
    steps:
      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :
      - name: Clone the repository
        uses: actions/checkout@v3
      - run: |
          cargo make --profile mainnet build-docker
          cargo make --profile mainnet build-xcc-docker
          cargo make --profile testnet build-docker
          cargo make --profile testnet build-xcc-docker
      - run: ls -lH bin/aurora-*.wasm
      - name: Update the latest releases
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: bin/aurora*.wasm
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
